version: '3'

services:
    nginx:
        build:
            context: $PWD/docker/context/nginx
            dockerfile: $PWD/docker/nginx
        restart: unless-stopped
        hostname: yunnet.ru
        tty: true
        ports:
            - "80:80"
            - "443:443"
        env_file:
            - $PWD/configs.env
        volumes:
            - $PWD/../../:/home/unt
            - /var/log/nginx
            - $PWD/config/nginx/nginx.conf:/etc/nginx/nginx.conf
        links:
            - php
        command: bash /home/unt/config/local/scripts/nginx.sh
    php:
        restart: unless-stopped
        stdin_open: true
        hostname: yunnet.ru
        tty: true
        build:
            context: $PWD/docker/context/php
            dockerfile: $PWD/docker/php
        env_file:
            - $PWD/configs.env
        volumes:
            - $PWD/../../:/home/unt
            - $PWD/config/php/php$UNT_PRODUCTION.ini:/usr/local/etc/php/php.ini
            - $PWD/config/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
            - $PWD/config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        links:
            - memcached
            - mail
        networks:
            - default
    memcached:
        image: memcached:latest
        container_name: memcached
    mail:
        restart: unless-stopped
        hostname: yunnet.ru
        tty: true
        build:
            dockerfile: $PWD/docker/postfix
            context: $PWD/docker/context/postfix
        volumes:
            - $PWD/../../:/home/unt
            - $PWD/config/postfix/exim4.conf.template:/etc/exim4/exim4.conf.template
            - $PWD/config/postfix:/etc/postfix
            - $PWD/config/postfix/mail-addresses:/etc/mail-addresses
        environment:
            - "MAILNAME=yunnet.ru"
            - "MAIN_FORCE_SENDER=yunnet.ru"
        env_file:
            - $PWD/configs.env
        ports:
            - "25:25"
    rabbitmq:
        restart: unless-stopped
        hostname: lp.yunnet.ru
        tty: true
        build:
            dockerfile: $PWD/docker/rabbitmq
            context: $PWD/docker/context/rabbitmq
        volumes:
            - $PWD/../../:/home/unt
        env_file:
            - $PWD/configs.env
    node:
        restart: unless-stopped
        hostname: yunnet.ru
        tty: true
        build:
            dockerfile: $PWD/docker/node
            context: $PWD/docker/context/node
        volumes:
            - $PWD/../../:/home/unt
        env_file:
            - $PWD/configs.env