name: lint

# push all commits to all branches
on:
  push

# lint uses only test server
env:
  UNT_PRODUCTION: 0

jobs:
  lint:
    name: Project lint
    runs-on: self-hosted
    steps:
      - name: Init PHP
        run: sudo -i apt-get update
            && cd ~/commits/}
            && echo PHP init setup succeded!
      - name: Setup variables
        run: |
                echo "git_branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_BRANCH &&
                echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_HASH &&
                echo "Current branch is ${{ GITHUB_BRANCH }}" &&
                echo "Current hash is ${{ GITHUB_HASH }}"
      - name: Download github differences
        run: |
                mkdir "$GIT_HASH" 
                && mkdir "$GIT_HASH"
                && cd $GIT_HASH
                && set PWD={pwd} 
                && echo Go to $PWD - OK! 
                && echo All operations OK! Clean up.
