name: lint

# push all commits to all branches
on:
  push

# lint uses only test server
env:
  UNT_PRODUCTION: 0

jobs:
  lint:
    name: Project lint
    runs-on: self-hosted
    steps:
      - name: Init project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0,
      - name: Fetching differences
        run: echo ::set-env name=GIT_DIFF::$(git diff  --stat -- './')
      - name: Validating files
        run: |
          echo Listing files diff.
          echo ${{ env.GIT_DIFF }}
